#!/usr/bin/env bash
# Wrapper script: sets up venv, fills .env, runs generate_advice.py
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$SCRIPT_DIR/.venv"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"

# -----------------------------------------------------------------------
# 1. Python venv
# -----------------------------------------------------------------------
if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment in $VENV_DIR ..."
    python3 -m venv "$VENV_DIR"
fi

# shellcheck disable=SC1091
source "$VENV_DIR/bin/activate"

echo "Installing dependencies..."
pip install -q -r "$SCRIPT_DIR/requirements.txt"

# -----------------------------------------------------------------------
# 2. Interactive .env setup (skip if .env already exists)
# -----------------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
    echo ""
    echo "======================================================================"
    echo "  First-time setup: let's configure your personal financial profile."
    echo "  All monetary values are in \$1,000 units (2023 USD)."
    echo "  Press Enter to accept the [default] shown in brackets."
    echo "======================================================================"
    echo ""

    read_val() {
        local prompt="$1" default="$2" var
        printf "  %s [%s]: " "$prompt" "$default"
        read -r var
        echo "${var:-$default}"
    }

    AGE=$(read_val "Your current age" "25")
    RET_AGE=$(read_val "Target retirement age" "65")
    NW=$(read_val "Current net worth (\$k)" "50")
    EXPENSES=$(read_val "Annual expenses (\$k/yr)" "40")
    FLOOR=$(read_val "Spending floor (\$k/yr, minimum tolerable)" "30")
    TAX=$(read_val "State tax rate (decimal, e.g. 0.05)" "0.05")

    echo ""
    echo "  Income schedule: comma-separated \$k/yr values, one per working year."
    echo "  Example: 75,75,100,100,120 means \$75k for 2 years, \$100k for 2, \$120k for 1."
    INCOME_DEFAULT="75,75,75,75,75,100,100,100,100,100,100,100,100,100,100,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120,120"
    printf "  Income schedule [press Enter for example schedule]: "
    read -r INCOME
    INCOME="${INCOME:-$INCOME_DEFAULT}"

    echo ""
    echo "  One-time expenses: age:amount pairs, comma-separated."
    echo "  Example: 30:150,40:50 means \$150k at age 30, \$50k at age 40."
    printf "  One-time expenses [none]: "
    read -r ONE_TIME
    ONE_TIME="${ONE_TIME:-}"

    cat > "$ENV_FILE" <<EOF
# Personal financial configuration
# Generated by run.sh on $(date +%Y-%m-%d)
# All monetary values in \$1,000 units (2023 USD)

START_AGE=$AGE
RETIREMENT_AGE=$RET_AGE
INITIAL_NET_WORTH=$NW
INITIAL_EXPENSES=$EXPENSES
SPENDING_FLOOR=$FLOOR
STATE_TAX_RATE=$TAX

INCOME_SCHEDULE=$INCOME

ONE_TIME_EXPENSES=$ONE_TIME
EOF

    echo ""
    echo "  Saved to $ENV_FILE"
    echo "  (Edit this file anytime to update your profile.)"
    echo ""
else
    echo "Using existing $ENV_FILE"
fi

# -----------------------------------------------------------------------
# 3. Run the analysis
# -----------------------------------------------------------------------
echo ""
echo "Running financial planning analysis..."
echo ""

export MPLBACKEND=Agg
python "$SCRIPT_DIR/generate_advice.py"

echo ""
echo "Done! Charts saved to $SCRIPT_DIR/assets/"
